### ISSUE TITLE
赤ずきんモーションの追加案

### ISSUE THREAD

**Issue by tiriyama-san** [K3-HelloWorld/PiyoPiyoChannel#7]
赤ずきんがジャンプするモーションを入れるなら、赤ずきんの被弾モーションをちょっと変えてもらえると、ジャンプの顔のモーションも作ることができますが、どうします？

**Comment by wamomo-san** [comment]
なるほど。ジャンプグラいれると、いいかもしれない。とりあえず作ってみます。
